### ISSUE TITLE
Please Add Version That DOESN'T Delete Steamapps Folder.

### ISSUE THREAD

**Issue by WallaWallas** [barrycarey/Ark_Mod_Downloader#1]
There is a current bug with steamCMD when downloading big workshop files, and that is the download will time out and fail to download the entire mod. When working with JUST steamCMD, this is ok, because you can retry downloading the same workshop item and it will pick up where it left. I am looking to download an Ark mod that is about 500 mb. It is able to complete about 70% of the download before the steamCMD timeout. However, instead of being able to retry and finish the download, the current version of the app will delete the steamapps folder and start over from 0%. 

Is there any way that you can create an alternate Ark_Mod_Downloader.exe that DOESN'T auto-delete the steamapps folder? Leaves it up to us to delete the folder instead?

Thanks!

**Comment by barrycarey** [comment]
I just added this option.  Include --preserve in the command line args to keep the SteamCMD content.
